### ISSUE TITLE
[Documentation] Network.Cancel

### ISSUE THREAD

**Issue by forslund** [heremaps/here-data-sdk-cpp#1246]
### Documentation
The Cancel method states that a Response should be send to the registered callback "marked as canceled" [here](https://github.com/heremaps/here-data-sdk-cpp/blob/master/olp-cpp-sdk-core/include/olp/core/http/Network.h#L98). How this is done isn't described (as far as I've been able to find) and a developer basically needs to search through the curl network implementation to find how it's done.

Could this be documented or even better a macro / subclass be provided for this?

### Which version/tag/hash of the HERE OLP SDK are you using?
latest master

**Comment by andescu** [comment]
@forslund Thanks for taking the time to report this. I'll extend the documentation with the expected output.
