### ISSUE TITLE
[BUG] Crash in NetworkCurl 

### ISSUE THREAD

**Issue by Hsilgos** [heremaps/here-data-sdk-cpp#1360]
### Describe the bug

Crash was detected during PSV on CI

### Which version/tag/hash of the HERE OLP SDK are you using?

master

### What compiler are you using? What version of the compiler?

clang from NDK 24.x

### Steps to reproduce the issue

Run integration tests many times (it's flaky).

### Can you provide any TRACE level logs?

Logs and symbolised stack are submitted 

[logs+crash.zip](https://github.com/heremaps/here-data-sdk-cpp/files/9879514/logs%2Bcrash.zip)

**Comment by andescu** [comment]
@Hsilgos Thanks for reporting the issue.
We are looking at the issue and will come back with a PR if it is valid or further questions if needed.

**Comment by Hsilgos** [comment]
After applying suggested fixes this issue doesn't appear
